### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by rovarghe** [gerritjvv/kafka-fast#18]
This project has a huge dependency list, which causes some conflict. 
Any chance of reducing it to bare minimum, maybe it more modular?
For example, redis client/jedis seems ortho to a kafka client, core.async has moved up from alpha, etc etc.

**Comment by gerritjvv** [comment]
hi, the kafka client uses a redis client to store its offsets, so that dependency cannot be removed. 
I've been thinking off upgrading to a latter version of core async, but you can already do that by just placing the latest core async into your leiningen project.clj.

Due to work commitments I'm not really able to spend too much time on limiting dependencies, maybe you can do this and contribute back?

**Comment by gerritjvv** [comment]
I've managed to remove some dependencies for now, thread-load, thread-exec which also referred to clj-tuple etc. Will have a look in the future on how to lessen the redis deps

**Comment by rovarghe** [comment]
Awesome! Thanks for the effort!

**Comment by gerritjvv** [comment]
update:

- upgraded all dependencies to latest released versions (using lein ancient),
- removed jedis
- redisson is still required because I can't seem to find how carmine works with redis cluster , which is a pain.

Closing this ticket for the moment as I cannot see more deps to remove. 

The latest version with the updated dependences is from 3.6.5-SNAPSHOT
https://github.com/gerritjvv/kafka-fast/pull/27
